### ISSUE TITLE
Question: Difference from awslogs driver

### ISSUE THREAD

**Issue by shinzui** [segmentio/ecs-logs#2]
When should you use ecs-logs now that the awslogs driver works well?

**Comment by achille-roussel** [comment]
For now the main (or only)

**Comment by achille-roussel** [comment]
Another upside to using ecs-logs is it keeps logs available via `docker logs` because it pulls them from the journal. With the awslogs driver logs aren't available via the standard `docker logs` command.
see https://docs.docker.com/engine/admin/logging/overview/

**Comment by shinzui** [comment]
Thank you for the answer. I was hoping that you would address the ability to fan out to multiple destinations because that's exactly what I'm looking for. The stream name is an issue for us so that's a good benefit and having the logs available via `docker logs` is useful, but the biggest problems is having the logs shipped outside of cloudwatch in an easy way. I see that you have a pull request to address that and I am looking forward to seeing it merged. 

Out of curiosity, could you please share your logging stack at segment.

**Comment by achille-roussel** [comment]
We're using loggly and elasticsearch to store and consume our logs, we're also experimenting with cloudwatch as we speak (currently deploying ecs-logs to prod as part of this).

The reason we didn't include these tools in stack was that we wanted it to be an AWS-only solution and not require external dependencies to other third-party services so it can be useful to as many as possible and not specific to the Segment use-case.
