### ISSUE TITLE
Question: ecs-logs recognised logging format.

### ISSUE THREAD

**Issue by caquino** [segmentio/ecs-logs#20]
Hi,

Is there any documentation available about the logging format accepted by ecs-logs?

I'm assuming that it's something necessary because of the last sentence on the README.md

_Note that it requires your service to output JSON formatted logs with with structure that ecs-logs recognize._

BTW: you have 2 "with" on this phrase at the README.md

**Comment by achille-roussel** [comment]
Thanks for reporting the typo!

I've updated the README with more details about the format ecs-logs supports, let me know if that answers your questions.

For the record, the structure definition is here: https://github.com/segmentio/ecs-logs/blob/master/lib/event.go#L61

**Comment by caquino** [comment]
Yes, it answers! thank you very much for the help and fast response!
