### ISSUE TITLE
Run task failed attribute error

### ISSUE THREAD

**Issue by cloudsan42** [segmentio/ecs-logs#45]
help needed I have created task definition for one of the app

Here is what i have given logconfiguration 

 "logConfiguration": {
        "logDriver": "journald",
        "options": {
          "tag": "nginx"
        }
When I run the task it is giving me failed attribute error ..can you please help what I have done wrong and when running ecs-egent i  mentioned env as ECS_AVAILABLE_LOGGING_DRIVERS=["journald"]

**Comment by achille-roussel** [comment]
Hello, would you be able to give me more details on the issue? Like the exact error message or a screenshot of what you see?

Also, can you confirm that you're running this on a Linux system that has systemd/journald (ubuntu 16.04 or others)?

**Comment by cloudsan42** [comment]
I'm Using coreOS 1122.2.0 when spinning  the Instance   with user-data to start ecs-egent and aws-logs..

#cloud-config

coreos:
 units:
   -
     name: amazon-ecs-agent.service
     command: start
     runtime: true
     content: |
       [Unit]
       Description=AWS ECS Agent
       Documentation=https://docs.aws.amazon.com/AmazonECS/latest/developerguide/
       Requires=docker.socket
       After=docker.socket

       [Service]
       Environment=ECS_CLUSTER=aetnaboostdev
       Environment=ECS_LOGLEVEL=info
       Environment=ECS_VERSION=latest
       Restart=on-failure
       RestartSec=30
       RestartPreventExitStatus=5
       SyslogIdentifier=ecs-agent
       ExecStartPre=-/bin/mkdir -p /var/log/ecs /var/ecs-data /etc/ecs 
       ExecStartPre=-/usr/bin/touch /etc/ecs/ecs.config
       ExecStartPre=-/usr/bin/docker kill ecs-agent
       ExecStartPre=-/usr/bin/docker rm ecs-agent
       ExecStartPre=/usr/bin/docker pull amazon/amazon-ecs-agent:${ECS_VERSION}
       ExecStart=/usr/bin/docker run --name ecs-agent \
                                     --env-file=/etc/ecs/ecs.config \
                                     --volume=/var/run/docker.sock:/var/run/docker.sock \
                                     --volume=/var/log/ecs:/log \
                                     --volume=/var/ecs-data:/data \
                                     --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
                                     --volume=/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro \
                                     --publish=127.0.0.1:51678:51678 \
                                     --env=ECS_CLUSTER=${ECS_CLUSTER} \
                                     --env=ECS_LOGLEVEL=${ECS_LOGLEVEL} \
                                     --env=ECS_LOGFILE=/log/ecs-agent.log
                                     --env=ECS_DATADIR=/data \
                                     --env=ECS_AVAILABLE_LOGGING_DRIVERS=["journald"] \
                                     amazon/amazon-ecs-agent:${ECS_VERSION}
   -
     name: amazon-ecs-logs.service
     command: start
     runtime: true
     content: |
       [Unit]
       Description=AWS ECS Logs
       Documentation=https://github.com/segmentio/ecs-logs
       Requires=docker.socket
       After=docker.socket
       
       [Service]
       Environment=ECS_CLUSTER=aetnaboostdev
       Environment=ECS_LOGLEVEL=info
       Environment=ECS_VERSION=latest
       Restart=on-failure
       RestartSec=30
       RestartPreventExitStatus=5
       SyslogIdentifier=ecs-logs
       ExecStartPre=-/bin/mkdir -p /run/logs/journal
       ExecStartPre=-/usr/bin/docker kill ecs-logs
       ExecStartPre=-/usr/bin/docker rm ecs-logs
       ExecStartPre=/usr/bin/docker pull segment/ecs-logs:${ECS_VERSION}
       ExecStart=/usr/bin/docker run --name ecs-logs \
                                     --volume /run/logs/journal:/run/logs/journal:ro \
                                     segment/ecs-logs:latest -src journald -dst cloudwatchlogs

Here is my  Task definition

{
  "requiresAttributes": [
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.journald"
    },
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    }
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:372741902294:task-definition/test:6",
  "networkMode": "bridge",
  "status": "ACTIVE",
  "revision": 6,
  "taskRoleArn": null,
  "containerDefinitions": [
    {
      "volumesFrom": [],
      "memory": 128,
      "extraHosts": null,
      "dnsServers": null,
      "disableNetworking": null,
      "dnsSearchDomains": null,
      "portMappings": [
        {
          "hostPort": 80,
          "containerPort": 80,
          "protocol": "tcp"
        }
      ],
      "hostname": null,
      "essential": true,
      "entryPoint": null,
      "mountPoints": [],
      "name": "nginx-container",
      "ulimits": null,
      "dockerSecurityOptions": null,
      "environment": [],
      "links": null,
      "workingDirectory": null,
      "readonlyRootFilesystem": null,
      "image": "nginx",
      "command": null,
      "user": null,
      "dockerLabels": null,
      "logConfiguration": {
        "logDriver": "journald",
        "options": {
          "tag": "nginx"
        }
      },
      "cpu": 0,
      "privileged": null,
      "memoryReservation": null
    }
  ],
  "volumes": [],
  "family": "test"
}

When I  run the Task I'm getting attribute error 

![image](https://cloud.githubusercontent.com/assets/16949648/19194588/52a3fa3e-8c6b-11e6-8026-7ded2f15d97e.png)

**Comment by achille-roussel** [comment]
Can you confirm the docker version you're using?

**Comment by cloudsan42** [comment]
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:        
 OS/Arch:      linux/amd64

**Comment by achille-roussel** [comment]
:/ I'm confused, everything looks like it's configured just fine. That being said, we only ever tested with docker 1.11 and 1.12 so I don't know if there could be issues with 1.10 (I doubt it tho).

Can you also confirm that things are working just fine if you remove the log configuration and ECS_AVAILABLE_LOGGING_DRIVERS env variable?

I think it would be worth checking that nothing else is overriding that environment variable (like something in the `--env-file=/etc/ecs/ecs.config`, even tho it should be empty from what I read)... just trying to wild guess what could go wrong here.

**Comment by cloudsan42** [comment]
Yes In Task definition if I  remove logconfiguration entries I was able to run the task..
and  /etc/ecs/ecs.config file is emtpy..

**Comment by cloudsan42** [comment]
Hi achille ,

I saw this message in ecs-agent.log

Invalid format for "ECS_AVAILABLE_LOGGING_DRIVERS" environment variable; expected a JSON array like ["json-file","syslog"]. err invalid character 'j' looking for beginning of value

Now also running docker 1.11.2 version on Coreos..

**Comment by achille-roussel** [comment]
Ah! systemd interprets the quotes in your config I think, so the variable ends being set to [journald] instead of ["journald"].
Try escaping the quotes ;)
