### ISSUE TITLE
datadog custom application metrics

### ISSUE THREAD

**Issue by nmarcetic** [segmentio/ecs-logs#52]
I saw you use dogstatsd client, does ecs-logs can be used for custom application metrics and datadog ?
I use segmentio/stack and ecs-logs to forward data from my instances to cloudwatch & ELK stack with custom data format, works like a charm. 
Now I need datadog agent for custom metrics from my services. 
Do I need to run datadog-agent on each of my instances ? Following for example http://docs.datadoghq.com/integrations/ecs/  or ecs-logs can help me with this ?

If you guys from segmentio have any other advice how to get datadog working with existing ecs cluster, that would be awesome :) Thanks!

**Comment by achille-roussel** [comment]
ecs-logs' integration with datadog is limited and cannot be used as a generic agent to send metrics to datadog.

You have to run a dogstatsd agent on each of the hosts you want to collect metrics from, you can use the standard dd-agent developed by datadog, or alternative implementation like [veneur](https://stripe.com/blog/introducing-veneur-high-performance-and-global-aggregation-for-datadog) for example.

**Comment by nmarcetic** [comment]
@achille-roussel All clear! Thanks a lot! Will check alternatives like veneur. Closing this one.
