### ISSUE TITLE
Why did the segment org on docker hub modify all the tags for many repos with `_deprecated`?

### ISSUE THREAD

**Issue by shidel-dev** [segmentio/ecs-logs#75]
Images on a public docker repo should not have existing tags removed/renamed.. This prevents the existing tags people might be relying on for their build/production infa to start to fail without any warning. 

This incident happened two days ago by a user called `clippyseg` on docker hub. I'm assuming that this has caused issues for a number of people. Some form of communication would have been appreciated.

**Comment by securityclippy** [comment]
Hey @shidel-dev!  It looks like this repo got caught up in some over-enthusiastic automation.  It was not our intention to deprecate public images.

As a quick fix, I've already pushed the `latest` and `stable` tags back to the repository, so those should work as of making this comment.

__I'm working on restoring ALL tags today and expect to be done by end of day today.__

So sorry for any issues this may have caused. I will update here again when all image tags have been restored.  Thanks for letting us know, we really appreciate it!

**Comment by securityclippy** [comment]
Update:  All image tags have been restored to their previous tag names and should all be back to normal. 

@shidel-dev  please let me know if you run into any further issues.  Again, my apologies for any issues this may have caused!
